cc_test(
    name = "rsp_tests",
    srcs = [
        "profiler_test_env.cpp",
        "test_active_scope.cpp",
        "test_api_enabled.cpp",
        "test_constexpr_string.cpp",
        "test_integration.cpp",
        "test_machine.cpp",
        "test_metadata.cpp",
        "test_profiler.cpp",
        "test_scope_info.cpp",
        "test_scope_manager.cpp",
        "test_serialization.cpp",
        "test_sinks.cpp",
        "test_slots.cpp",
        "test_threading.cpp",
    ],
    defines = ["RSP_ENABLE"],
    deps = [
        "//:rsp",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "rsp_tests_disabled",
    srcs = ["test_api_disabled.cpp"],
    deps = [
        "//:rsp",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
