// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RSP

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetadataEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetadataEntry(buf []byte, offset flatbuffers.UOffsetT) *MetadataEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetadataEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetadataEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetadataEntry(buf []byte, offset flatbuffers.UOffsetT) *MetadataEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetadataEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetadataEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetadataEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetadataEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetadataEntry) Tag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetadataEntry) Type() MetadataType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MetadataType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MetadataEntry) MutateType(n MetadataType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *MetadataEntry) Value() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetadataEntry) MutateValue(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func MetadataEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MetadataEntryAddTag(builder *flatbuffers.Builder, tag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tag), 0)
}
func MetadataEntryAddType(builder *flatbuffers.Builder, type_ MetadataType) {
	builder.PrependInt8Slot(1, int8(type_), 0)
}
func MetadataEntryAddValue(builder *flatbuffers.Builder, value uint64) {
	builder.PrependUint64Slot(2, value, 0)
}
func MetadataEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
