// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RSP

import "strconv"

type MetadataType int8

const (
	MetadataTypeUNSET  MetadataType = 0
	MetadataTypeINT8   MetadataType = 1
	MetadataTypeUINT8  MetadataType = 2
	MetadataTypeINT16  MetadataType = 3
	MetadataTypeUINT16 MetadataType = 4
	MetadataTypeINT32  MetadataType = 5
	MetadataTypeUINT32 MetadataType = 6
	MetadataTypeINT64  MetadataType = 7
	MetadataTypeUINT64 MetadataType = 8
	MetadataTypeFLOAT  MetadataType = 9
	MetadataTypeDOUBLE MetadataType = 10
)

var EnumNamesMetadataType = map[MetadataType]string{
	MetadataTypeUNSET:  "UNSET",
	MetadataTypeINT8:   "INT8",
	MetadataTypeUINT8:  "UINT8",
	MetadataTypeINT16:  "INT16",
	MetadataTypeUINT16: "UINT16",
	MetadataTypeINT32:  "INT32",
	MetadataTypeUINT32: "UINT32",
	MetadataTypeINT64:  "INT64",
	MetadataTypeUINT64: "UINT64",
	MetadataTypeFLOAT:  "FLOAT",
	MetadataTypeDOUBLE: "DOUBLE",
}

var EnumValuesMetadataType = map[string]MetadataType{
	"UNSET":  MetadataTypeUNSET,
	"INT8":   MetadataTypeINT8,
	"UINT8":  MetadataTypeUINT8,
	"INT16":  MetadataTypeINT16,
	"UINT16": MetadataTypeUINT16,
	"INT32":  MetadataTypeINT32,
	"UINT32": MetadataTypeUINT32,
	"INT64":  MetadataTypeINT64,
	"UINT64": MetadataTypeUINT64,
	"FLOAT":  MetadataTypeFLOAT,
	"DOUBLE": MetadataTypeDOUBLE,
}

func (v MetadataType) String() string {
	if s, ok := EnumNamesMetadataType[v]; ok {
		return s
	}
	return "MetadataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
