// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RSP

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScopeInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsScopeInfo(buf []byte, offset flatbuffers.UOffsetT) *ScopeInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScopeInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishScopeInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScopeInfo(buf []byte, offset flatbuffers.UOffsetT) *ScopeInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScopeInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScopeInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScopeInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScopeInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScopeInfo) Tag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScopeInfo) TicksStart() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScopeInfo) MutateTicksStart(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ScopeInfo) TicksEnd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScopeInfo) MutateTicksEnd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ScopeInfo) MachineNominalFreqHz() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScopeInfo) MutateMachineNominalFreqHz(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *ScopeInfo) MaxBufferSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScopeInfo) MutateMaxBufferSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *ScopeInfo) MaxOffset() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScopeInfo) MutateMaxOffset(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *ScopeInfo) Metadata(obj *MetadataEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ScopeInfo) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ScopeInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ScopeInfoAddTag(builder *flatbuffers.Builder, tag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tag), 0)
}
func ScopeInfoAddTicksStart(builder *flatbuffers.Builder, ticksStart uint64) {
	builder.PrependUint64Slot(1, ticksStart, 0)
}
func ScopeInfoAddTicksEnd(builder *flatbuffers.Builder, ticksEnd uint64) {
	builder.PrependUint64Slot(2, ticksEnd, 0)
}
func ScopeInfoAddMachineNominalFreqHz(builder *flatbuffers.Builder, machineNominalFreqHz uint64) {
	builder.PrependUint64Slot(3, machineNominalFreqHz, 0)
}
func ScopeInfoAddMaxBufferSize(builder *flatbuffers.Builder, maxBufferSize uint64) {
	builder.PrependUint64Slot(4, maxBufferSize, 0)
}
func ScopeInfoAddMaxOffset(builder *flatbuffers.Builder, maxOffset byte) {
	builder.PrependByteSlot(5, maxOffset, 0)
}
func ScopeInfoAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(metadata), 0)
}
func ScopeInfoStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ScopeInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
